/****** Script for SelectTopNRows command from SSMS  ******/
SELECT * FROM [TeduIdentity].[dbo].[ServerSideSessions]
SELECT * FROM [TeduIdentity].[dbo].[DeviceCodes]
SELECT * FROM [TeduIdentity].[dbo].[Keys]
SELECT * FROM [TeduIdentity].[dbo].[PersistedGrants]
SELECT * FROM [TeduIdentity].[dbo].[PushedAuthorizationRequests]
--------------
SELECT * FROM [TeduIdentity].[dbo].[ApiResourceClaims]
SELECT * FROM [TeduIdentity].[dbo].[ApiResourceProperties]
SELECT * FROM [TeduIdentity].[dbo].[ApiResources]
SELECT * FROM [TeduIdentity].[dbo].[ApiResourceScopes]
SELECT * FROM [TeduIdentity].[dbo].[ApiResourceSecrets]
SELECT * FROM [TeduIdentity].[dbo].[ApiScopeClaims]
SELECT * FROM [TeduIdentity].[dbo].[ApiScopeProperties]
SELECT * FROM [TeduIdentity].[dbo].[ApiScopes]
-------------
SELECT * FROM [TeduIdentity].[dbo].[ClientClaims]
SELECT * FROM [TeduIdentity].[dbo].[ClientCorsOrigins]
SELECT * FROM [TeduIdentity].[dbo].[ClientGrantTypes]
SELECT * FROM [TeduIdentity].[dbo].[ClientIdPRestrictions]
SELECT * FROM [TeduIdentity].[dbo].[ClientPostLogoutRedirectUris]
SELECT * FROM [TeduIdentity].[dbo].[ClientProperties]
SELECT * FROM [TeduIdentity].[dbo].[ClientRedirectUris]
SELECT * FROM [TeduIdentity].[dbo].[Clients]
SELECT * FROM [TeduIdentity].[dbo].[ClientScopes]
SELECT * FROM [TeduIdentity].[dbo].[ClientSecrets]
-------------
SELECT * FROM [TeduIdentity].[dbo].[IdentityProviders]
SELECT * FROM [TeduIdentity].[dbo].[IdentityResourceClaims]
SELECT * FROM [TeduIdentity].[dbo].[IdentityResourceProperties]
SELECT * FROM [TeduIdentity].[dbo].[IdentityResources]